<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // The ERD migration created suppliers with only id/timestamps.
        // Add all business columns now, including origin (Local|International) and region.
        Schema::table('suppliers', function (Blueprint $table) {
            $table->string('supplier_name', 255)->after('id');
            $table->string('contact_person', 255)->nullable()->after('supplier_name');
            $table->string('contact_number', 20)->nullable()->after('contact_person');
            $table->string('email', 100)->nullable()->after('contact_number');
            $table->text('address')->nullable()->after('email');
            // Origin classifies the supplier as Local (Philippines) or International
            $table->string('origin', 20)->default('Local')->after('address');
            // Region is a controlled dropdown derived from the selected origin
            $table->string('region', 100)->nullable()->after('origin');
            $table->string('tin', 50)->nullable()->after('region');
            $table->unsignedBigInteger('status_id')->nullable()->after('tin');
            $table->text('notes')->nullable()->after('status_id');
            $table->softDeletes();

            $table->foreign('status_id')
                ->references('status_id')
                ->on('status_lookup')
                ->onDelete('set null');
        });

        // Junction table: many-to-many between suppliers and products
        Schema::create('supplier_product', function (Blueprint $table) {
            $table->id('supplier_prod_id');
            $table->unsignedBigInteger('supplier_id');
            $table->unsignedBigInteger('product_id');
            $table->decimal('product_price', 10, 2)->nullable();
            $table->string('currency', 10)->default('PHP');
            $table->unsignedBigInteger('status_id')->nullable();
            $table->timestamps();

            // suppliers PK is 'id' (auto-generated by the ERD migration)
            $table->foreign('supplier_id')
                ->references('id')
                ->on('suppliers')
                ->onDelete('cascade');

            $table->foreign('product_id')
                ->references('product_id')
                ->on('products')
                ->onDelete('cascade');

            $table->foreign('status_id')
                ->references('status_id')
                ->on('status_lookup')
                ->onDelete('set null');

            $table->unique(['supplier_id', 'product_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('supplier_product');

        Schema::table('suppliers', function (Blueprint $table) {
            $table->dropForeign(['status_id']);
            $table->dropColumn([
                'supplier_name', 'contact_person', 'contact_number', 'email',
                'address', 'origin', 'region', 'tin', 'status_id', 'notes', 'deleted_at',
            ]);
        });
    }
};
